server:
  port: 9920
spring:
  datasource:
    username: root
    password: anzhen3531
    url: jdbc:mysql://:3306/imageprodect?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
# minio 参数配置
minio:
  #  endpoint: http://182.42.116.193
  endpoint: http://192.168.1.4
  port: 9000
  accessKey: admin
  secretKey: anzhen3531
  bucket: wallhaven-photo