server:
  port: 9920
spring:
  datasource:
    username: root
    password: anzhen3531
    url: jdbc:mysql://120.26.48.34:3306/imageprodect?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 120.26.48.34
    database: 1
    port: 6379
  main:
    allow-bean-definition-overriding: true



logging:
  level:
    com.anzhen.mapper: DEBUG
    root: INFO
# minio 参数配置

# 26d3bee4fa42c7544f118774154176dc8679bbb0 密钥
# 1c5c71a9fc77bea14869 client账号


minio:
  #  endpoint: http://127.0.0.1
#  endpoint: http://172.17.0.1
  endpoint: http://120.26.48.34
  #  endpoint: http://182.42.116.193
  port: 9000
  accessKey: root
  #  accessKey: admin
  secretKey: root123456
  #  secretKey: anzhen3531
  bucket: wallhaven-photo

github:
  clientId: 1c5c71a9fc77bea14869
  clientSecret: 26d3bee4fa42c7544f118774154176dc8679bbb0
  redirectUri: http://localhost:8080/login

